
name: Pytest Keypoint Detector

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: gitlab+deploy-token-8:YHsqg1MHW-C4GJpr_B-D@gitlab.ilabt.imec.be:4567/tlips/gpulab/jupyterlab-pytorch:latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare and build
        run: |
          cd keypoint_detection
          source /opt/conda/bin/activate
          conda activate python39
          pip install -e  box-manipulation/keypoint_detection
          pytest .
        shell: bash
